import type { Metadata } from 'next'
import './globals.css'
import { Footer, MainNavigation, ScrollToTop } from '@/components'
import Providers from '@/app/providers'
import { Box, Container } from '@mui/material'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <body>
        <Providers>
          <MainNavigation />

          <Box component='main' bgcolor='#f3f4fd' pt='100px' pb={'50px'}>
            <Container maxWidth='lg'>{children}</Container>
            <ScrollToTop />
          </Box>

          <Footer />
        </Providers>
      </body>
    </html>
  )
}